#!/bin/bash
set -x
export THISDIR=$(pwd)
if [[ ! $0  -ef ${THISDIR}/src/doall ]] ; then
  echo 'error in $0: must be called from parent directory'
  exit 1
fi

bash src/doit_malo
bash src/doit_iron
bash src/doit_pmo
bash src/doit_analyze
